title: "Samuel's Portfolio"
email: "ballu.samu@gmail.com"
description: "Master’s Degree in MAS, AI Pathway - My personal portfolio"
url: "https://TonNomUtilisateur.github.io"
theme: jekyll-theme-midnight # thème
github_username: Minimugule
mail : ballu.samu@gmail.com
linkedin_username: Samuel Ballu


# Navigation
header_pages:
  - index.md
  - projects.md
